spring.application.name=EmployeeManagementProject

spring.datasource.url=jdbc:mysql://localhost:3306/employeesystem
spring.datasource.username=Your_Username
spring.datasource.password= Your_Password

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
